baseURL = "https://www.joeybuiteweg.com/"
defaultContentLanguage = "en-us"
languageCode = "en-us"
title = "Joey Buiteweg"
enableRobotsTXT = true
[params]
  author = "Joey Buiteweg"
  description = "Joey's Personal Website/Blog"
  gravatar = "joey@joeybuiteweg.com"

[taxonomies]
category = "categories"

[privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.youtube]
    privacyEnhanced = true

[markup]
    [markup.highlight]
    style = "dracula"
