baseURL = "https://www.josephbuiteweg.com/"
languageCode = "en-us"
title = "Joseph Buiteweg"
[params]
  author = "Joseph Buiteweg"
  description = "Joey's Personal Website/Blog"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    identifier = "music"
    name = "Music"
    url = "/music/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

  # [[menu.main]]
  #   identifier = "dei"
  #   name = "DEI"
  #   url = "/dei/"
  #   weight = 4

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
